"""unique constraint and phase 11 columns

Revision ID: 2fb7994c49bc
Revises: bc6f4bc61f30
Create Date: 2026-06-09 10:00:19.097601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb7994c49bc'
down_revision: Union[str, Sequence[str], None] = 'bc6f4bc61f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correlations', sa.Column('service_name', sa.String(length=100), nullable=True))
    op.add_column('correlations', sa.Column('host_name', sa.String(length=100), nullable=True))
    op.add_column('correlations', sa.Column('container_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_correlations_created_at'), 'correlations', ['created_at'], unique=False)
    op.create_unique_constraint('uq_metric_log_correlation', 'correlations', ['metric_anomaly_id', 'log_anomaly_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_metric_log_correlation', 'correlations', type_='unique')
    op.drop_index(op.f('ix_correlations_created_at'), table_name='correlations')
    op.drop_column('correlations', 'container_id')
    op.drop_column('correlations', 'host_name')
    op.drop_column('correlations', 'service_name')
    # ### end Alembic commands ###
